#!/bin/bash
# send a notification for low battery every minute
# * * * * * ~/.scripts/cron_bat

THRESHOLD=10

B0="/sys/class/power_supply/BAT0"
B1="/sys/class/power_supply/BAT1"

if [[ $(cat $B0/status) != 'Charging' ]] && [[ $(cat $B1/status) != 'Charging' ]] && [[ $(cat $B0/capacity) -le $THRESHOLD ]] && [[ $(cat $B1/capacity) -le $THRESHOLD ]]; then
	DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus /usr/bin/notify-send -u critical "Out of juice" "Please charge me battery"
fi
