#!/bin/python
# downloads subtitles for given media file from yifysubtitles.com 

from bs4 import BeautifulSoup
import requests, sys, os, re, zipfile

def get_ytsdl(movie_name, file_name):
    s = requests.session()
    root = "https://yifysubtitles.com"
    url = root + "/search?q=" + movie_name.replace(' ','+')
    movies = BeautifulSoup(s.get(url).text, 'html.parser').find_all('div','media-body')
    
    if len(movies)==0: print('No subtitles found'); exit(0)
    print('Movie found looking for subtitles..')

    if len(movies)>1:
        for i in range(len(movies)): print(i,movies[i].find('h3','media-heading').text)
        url = root + movies[int(input('Enter movie number to download: '))].find('a')['href']
    else: url = root + movies[0].find('a')['href']

    eng_srt = BeautifulSoup(s.get(url).text, 'html.parser').find('span','sub-lang',text='English')
    if eng_srt is None: print('No subtitles found'); exit(0)

    url = root + eng_srt.parent.next_sibling.find('a')['href']
    url = BeautifulSoup(s.get(url).text, 'html.parser').find('a','btn-icon download-subtitle')['href']

    r = s.get(url)
    ext = url.split('.')[-1]
    with open('temp.'+ext, 'wb') as f:
        for chunk in r.iter_content(chunk_size=1024):
            if chunk: f.write(chunk)
    if ext=='zip':
        zip_ref = zipfile.ZipFile('temp.zip', 'r')
        zip_ref.extractall('.')
        os.rename(zip_ref.filelist[0].filename, file_name)
        for zipInfo in zip_ref.filelist[1:]:
            os.remove(zipInfo.filename)
        zip_ref.close()
    os.remove('temp.zip')
    print('done')

if __name__ == "__main__":
    if len(sys.argv)!=2:
        print('Usage yify_dl <file_name>')
        exit(0)
    movie_name = input('Enter movie name: ')
    file_name = os.path.splitext(sys.argv[1])[0] + '.srt'
    get_ytsdl(movie_name, file_name)
